//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHPLS11.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhpTaiKhoan
    {
        public int NhpId { get; set; }
        public string NhpUserName { get; set; }
        public string NhpPassword { get; set; }
        public string NhpFullName { get; set; }
        public Nullable<int> NhpAge { get; set; }
        public string NhpEmail { get; set; }
        public string NhpPhone { get; set; }
        public Nullable<bool> NhpStatus { get; set; }
    }
}
