//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHPLesson09.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhpKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nhpKhoa()
        {
            this.nhpSinhVien = new HashSet<nhpSinhVien>();
        }
    
        public string NhpMaKH { get; set; }
        public string NhpTenKH { get; set; }
        public Nullable<bool> NhpTrangthai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nhpSinhVien> nhpSinhVien { get; set; }
    }
}
