//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHPLesson09.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NHPK22CNT1Ls09Entities : DbContext
    {
        public NHPK22CNT1Ls09Entities()
            : base("name=NHPK22CNT1Ls09Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<nhpKhoa> nhpKhoa { get; set; }
        public virtual DbSet<nhpSinhVien> nhpSinhVien { get; set; }
    }
}
