//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHPLesson09.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhpSinhVien
    {
        public string NhpMaSV { get; set; }
        public string NhpHoSV { get; set; }
        public string NhpTenSV { get; set; }
        public Nullable<System.DateTime> NhpNgaySinh { get; set; }
        public Nullable<bool> NhpPhai { get; set; }
        public string NhpPhone { get; set; }
        public string NhpEmail { get; set; }
        public string NhpMaKH { get; set; }
    
        public virtual nhpKhoa nhpKhoa { get; set; }
    }
}
